name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: laravel_database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Set up MySQL
      run: |
        sudo mysql -e "CREATE DATABASE laravel_database;"
        sudo mysql -e "CREATE USER 'laravel_user'@'%' IDENTIFIED BY 'password';"
        sudo mysql -e "GRANT ALL ON laravel_database.* TO 'laravel_user'@'%';"
    - name: Modify .env file for MySQL
      run: |
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_DATABASE=database\/database.sqlite/DB_DATABASE=laravel_database/' .env
        sed -i 's/DB_USERNAME=/DB_USERNAME=laravel_user/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
